### ISSUE TITLE
Missing images in data

### ISSUE THREAD

**Issue by cooleel** [ShuoZhang2003/DT-VQA#1]
I downloaded the data from [huggingface](https://huggingface.co/shuozhang2/DT-VQA), but looks like there is no DTTabShot images in there.  Could you please take a look?

**Comment by ShuoZhang2003** [comment]
Sorry, the "DTTabFact" in the image folder contains the "DTTabShot" part of the image. Actually it is a folder naming error.

**Comment by cooleel** [comment]
Oh. okay. thanks for confirmating. 
yeah, it doesn't have all images in DTTabShot, Is it possible to provide the full dataset?

**Comment by cooleel** [comment]
Never mind. It has all images. I changed the folder name and it worked fine. I will close this issue. 
Thanks.
